AutoBalance.Enable.Global = 1
AutoBalance.Enable.5M = 1
AutoBalance.Enable.10M = 1
AutoBalance.Enable.15M = 1
AutoBalance.Enable.20M = 1
AutoBalance.Enable.25M = 1
AutoBalance.Enable.40M = 1
AutoBalance.Enable.OtherNormal = 1
AutoBalance.Enable.5MHeroic = 1
AutoBalance.Enable.10MHeroic = 1
AutoBalance.Enable.25MHeroic = 1
AutoBalance.Enable.OtherHeroic = 1
AutoBalance.MinPlayers = 1
AutoBalance.MinPlayers.Heroic = 1
AutoBalance.MinPlayers.Raid = 1
AutoBalance.MinPlayers.RaidHeroic = 1
AutoBalance.InflectionPointRaid = 0.5
AutoBalance.StatModifier.Global = 1.0
AutoBalance.StatModifierRaid.Global = 1.0
AutoBalance.StatModifierRaid.Damage = 1.0
AutoBalance.StatModifierRaid.Health = 1.0
