AuctionHouseBot.EnableSeller = 0
AuctionHouseBot.EnableBuyer = 0
AuctionHouseBot.Account = 0
AuctionHouseBot.GUID = 0
AuctionHouseBot.VendorItems = 0
AuctionHouseBot.VendorTradeGoods = 1
AuctionHouseBot.LootItems = 1
AuctionHouseBot.LootTradeGoods = 1
AuctionHouseBot.OtherItems = 0
AuctionHouseBot.OtherTradeGoods = 1
AuctionHouseBot.ProfessionItems = 1
AuctionHouseBot.ItemsPerCycle = 200
AuctionHouseBot.ElapsingTimeClass = 1
AuctionHouseBot.DivisibleStacks = 1
