# Общий overlay для worldserver.conf (все варианты)
RealmZone = 12
DeclinedNames = 1
DBC.Locale = 0
SupportedLocales = 0,8
EnablePlayerSettings = 1
DBC.EnforceItemAttributes = 0
Updates.EnableDatabases = 7
MaxPrimaryTradeSkill = 11
MapUpdate.Threads = 4
PreloadAllNonInstancedMapGrids = 0
MinWorldUpdateTime = 1
Expansion = 2
GameType = 0
Ra.EnableRA = 0
SOAP.Enabled = 0
PlayerStart.AllReputation = 0
ListenRange.Say = 40
ListenRange.TextEmote = 40
ListenRange.Yell = 300
Rate.Rest.InGame = 1
Rate.XP.Kill = 1
Rate.XP.Quest = 1
Rate.XP.Explore = 1
MaxOverspeedPings = 0
Network.Threads = 1
Network.OutKBuff = -1
Network.OutUBuff = 65536
Network.TcpNoDelay = 1
WorldServerPort = 8085
BindIP = "0.0.0.0"
Console.Enable = 1
Ra.IP = "0.0.0.0"
LogLevel = 2
