AiPlayerbot.Enabled = 1
AiPlayerbot.RandomBotAutologin = 1
AiPlayerbot.MinRandomBots = 200
AiPlayerbot.MaxRandomBots = 200
AiPlayerbot.SyncLevelWithPlayers = 1
AiPlayerbot.GroupInvitationPermission = 2
AiPlayerbot.AddClassCommand = 1
AiPlayerbot.MaxAddedBots = 40
AiPlayerbot.RandomBotMinLevel = 1
AiPlayerbot.RandomBotMaxLevel = 80
AiPlayerbot.RandomBotInvitePlayer = 0
AiPlayerbot.DisabledWithoutRealPlayer = 0
AiPlayerbot.BotActiveAlone = 100
AiPlayerbot.BotActiveAloneForceWhenInZone = 1
AiPlayerbot.BotActiveAloneForceWhenInRadius = 150
AiPlayerbot.EnableRandomBotTrading = 1
AiPlayerbot.LimitTalentsExpansion = 1
AiPlayerbot.RandomBotAccountPrefix = "rndbot"
