# Форк trickerer/mod-autobalance считает нанятых NPCBots игроками.
AutoBalance.Enable.Global = 1
AutoBalance.CountNpcBots = 1
AutoBalance.MinPlayers = 1
AutoBalance.MinPlayers.Raid = 1
AutoBalance.InflectionPointRaid = 0.5
