NpcBot.Enable = 1
NpcBot.Enable.Dungeon = 1
NpcBot.Enable.Raid = 1
NpcBot.Enable.DungeonFinder = 1
NpcBot.Enable.BG = 0
NpcBot.Enable.Arena = 0
NpcBot.Limit.Dungeon = 0
NpcBot.Limit.Raid = 0
NpcBot.MaxBotsPerAccount = 4
NpcBot.MaxBotsPerClass = 1
NpcBot.WanderingBots.Continents.Count = 0
NpcBot.HideSpawns = 0
AllowTwoSide.Interaction.Group = 1
AllowTwoSide.Interaction.Chat = 1
AllowTwoSide.WhoList = 1
